export default {
    mainView:{
        display:'flex',
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'column',
        flex:1,
        padding:10,
        backgroundColor:'#fff'
    },
    innerMainView:{
        backgroundColor:'#f1f1f1',
        alignSelf:'stretch',
        elevation:4,
        borderRadius:3
    },
    textInputStyle:{
        minWidth:250,
        fontSize:25,
        textAlign:'center',
        paddingVertical:30,
        borderBottomWidth:1,
        borderBottomColor:'#d0d0d0'
    },
    textInputStyle2:{
        minWidth:250,
        fontSize:25,
        textAlign:'center',
        paddingVertical:30,
        borderTopWidth:1,
        borderTopColor:'#d0d0d0'
    },
    formulaBar:{
        display:'flex',
        flexDirection:'row',
        padding:10
    },
    editView:{
        flex:1,
        display:'flex',
        justifyContent:'center',
        alignItems:'center'
    },
    editButtonStyle:{
        flex:1,
        borderRadius:0
    },
    selectedFormulaStyle:{
        backgroundColor:'#607d8b',
        padding:10,
        borderRadius:3
    },
    selectedFormulaTextStyle:{
        paddingHorizontal:15,
        color:'#fff',
        fontWeight:'600'
    },
    formulaInnnerView:{
        padding:10,
        borderRadius:3
    },
    formulaInnnerText:{
        paddingHorizontal:15,
        fontWeight:'600'
    },
    buttonStyle:{
        paddingVertical:30
    },
    viewFormulaStyle:{
        backgroundColor:'#fff',
        borderWidth:2,
        borderColor:'#607d8b',
        elevation:0
    },
    viewFormulaTextStyle:{
        color:'#607d8b',
        fontWeight:'600'
    }

}